apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atc-transcript-analyzer

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: atc-frontend
  app.kubernetes.io/component: frontend
